inpresystem/apps/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('createNewText/', views.create_text_button, name = 'create_text_button'),
    path('find/', views.find_button, name = 'find_button'),
    path('sort/', views.sort_button, name = 'sort_button'),
    path('save_<int:text_id>/', views.save_text, name = 'save_text'),
    path('view_<int:text_id>/', views.review_text, name = 'review_text'),
    path('delete_<int:text_id>/', views.delete_text, name = 'delete_text'),
    path('created/', views.create_text, name = 'create_text')
]

inpresystem/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
]

inpresystem/apps/main/models.py
import datetime
from django.db import models

from django.utils import timezone

inpresystem/apps/main/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from bs4 import BeautifulSoup as Soup
import xml.etree.ElementTree as xml

url = 'http://127.0.0.1:8000/'
object = None
sortState = 0

#visible, hidden, inherit

class my_object:
    id = ""
    source = ""
    category = ""
    published = ""
    title = ""
    text = ""
    def __init__(self, id, source, category, published, title, text):
        self.id = id
        self.source = source
        self.category = category
        self.published = published
        self.title = title
        self.text = text

class my_objects:
    list_of_objects = []
    find_list_of_objects = []
    actual_list_of_objects = []
    objects = {}
    count = 0
    xml_name = ''
    find_mode = 0
    find_string = ''
    id = 1
    def __init__(self, xml_name):
        self.xml_name = xml_name
        self.list_of_objects = []
        self.objects = {}
        self.count = 0
        with open(xml_name, 'r', encoding='utf-8') as xml:
            soup = Soup(xml.read(), 'lxml')
            for doc in soup.find_all('doc'):
                self.list_of_objects.append(my_object(doc.find('id').text, 
                                                 doc.find('source').text,
                                                 doc.find('category').text,
                                                 doc.find('published').text,
                                                 doc.find('title').text,
                                                 doc.find('text').text))
                self.objects[doc.find('id').text] = self.count
                self.id = int(doc.find('id').text)
                self.count+=1
        self.updateActualList()

    def updateActualList(self):
        global sortState
        sortState = 0
        if self.find_mode == 0:
            self.actual_list_of_objects = self.list_of_objects
        else:
            self.actual_list_of_objects = self.find_list_of_objects

    def create(self, source, category, published, title, text):
        self.list_of_objects.append(my_object(self.id+1, 
                                              source,
                                              category,
                                              published,
                                              title,
                                              text))
        self.save_xml()
    
    def update(self, id, source, category, published, title, text):
        project = self.list_of_objects[int(self.objects.get(f'{int(id)}'))]
        #project.id = id
        project.source = source
        project.category = category
        project.published = published
        project.title = title
        project.text = text
        self.save_xml()

    def delete(self, text_id):
        tmp = self.list_of_objects.pop(int(self.objects.get(f'{int(text_id)}')))
        print(f'UDALYAEM {tmp.id}')
        self.find_string = ''
        self.find_mode = 0
        self.save_xml()

    def find(self, find_str):
        if find_str=='':
            self.find_mode = 0
            self.find_string = find_str
        else:
            self.find_mode = 1
            self.find_string = find_str
        self.find_list_of_objects = []
        find_str = self.find_string.lower()
        for i in self.list_of_objects:
            if i.title.lower().find(find_str) != -1:
                self.find_list_of_objects.append(i)
        self.updateActualList()

    def sort(self, sortState):
        if sortState == 1: #По возрастания
            self.actual_list_of_objects = sorted(self.actual_list_of_objects, key=lambda x: x.title)
        elif sortState == 2: #По убыванию
            self.actual_list_of_objects = sorted(self.actual_list_of_objects, key=lambda x: x.title, reverse=True)
        else: #По умолчанию
            self.updateActualList()

    #Создать корень xml-файла
    def createRootXML(self):
        return xml.Element("docs")

    #Создать итоговый xml-файл
    def createXML(self, root, filename):
        tree = xml.ElementTree(root)
        tree.write(filename, encoding='utf8')

    #Добавить элемент в xml-файл
    def appendRootXML(self, root, element):
        global lock
        root.append(element)

    #Создать XML-элемент
    def createElement(self, **args)->xml.Element:
        xml_root = xml.Element("doc")
        xml_contents = []
        xml_count = 0
        for j, i in args.items():
            xml_contents.append(xml.SubElement(xml_root, j))
            xml_contents[xml_count].set('auto','false')
            xml_contents[xml_count].set('type','str')
            xml_contents[xml_count].set('verify','true')
            xml_contents[xml_count].text = str(i)
            xml_count+=1
        return xml_root

    def save_xml(self):
        xml_root = self.createRootXML()

        for i in self.list_of_objects:
            root = self.createElement(id=i.id, 
                                      source=i.source, 
                                      category=i.category, 
                                      published=i.published, 
                                      title=i.title, 
                                      text=i.text)
            self.appendRootXML(xml_root, root)

        self.createXML(xml_root, self.xml_name)
        self.__init__(self.xml_name)

def index(request):
    global object
    print('INDEX')
    object = my_objects('result.xml')
    return render(request, 'main/index.html', {'url':url, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'hidden'})

def create_text_button(request):
    global object
    print('CREATEOBJECTBUTTON')
    return render(request, 'main/index.html', {'url':url, 'xml_file':object, 'CPVisibility':'visible', 'RPVisibility':'hidden'})

def find_button(request):
    global object
    find_str = request.POST.get('find', 'N/D')
    print(f'FINDBUTTON: {find_str}')
    object.find(find_str)
    return render(request, 'main/index.html', {'url':url, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'hidden'})

def sort_button(request):
    global object
    global sortState
    if sortState>=2:
        sortState=0
    else:
        sortState+=1
    print(f'SORTBUTTON: {sortState}')
    object.sort(sortState)
    return render(request, 'main/index.html', {'url':url, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'hidden'})

def create_text(request):
    global object
    print('CREATEOBJECT')
    object.create(request.POST.get('source', 'N/D'),
                  request.POST.get('category', 'N/D'),
                  request.POST.get('published', 'N/D'),
                  request.POST.get('title', 'N/D'),
                  request.POST.get('text', 'N/D'))
    text = object.list_of_objects[int(object.objects.get(f'{object.id}'))]
    return render(request, 'main/index.html', {'url':url, 'text':text, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'visible'})

def save_text(request, text_id):
    global object
    print('SAVEOBJECT: '+str(text_id))
    object.update(text_id,
                request.POST.get('source', 'N/D'),
                request.POST.get('category', 'N/D'),
                request.POST.get('published', 'N/D'),
                request.POST.get('title', 'N/D'),
                request.POST.get('text', 'N/D'))
    text = object.list_of_objects[int(object.objects.get(f'{int(text_id)}'))]
    return render(request, 'main/index.html', {'url':url, 'text':text, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'visible'})

def delete_text(request, text_id):
    global object
    print('DELETEOBJECT: '+str(text_id))
    object.delete(text_id)
    return render(request, 'main/index.html', {'url':url, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'hidden'})

def review_text(request, text_id):
    global object
    print('REVIEWOBJECT: '+str(text_id))
    text = object.list_of_objects[int(object.objects.get(f'{int(text_id)}'))]
    print(object.list_of_objects[int(object.objects.get(f'{int(text_id)}'))].id)
    return render(request, 'main/index.html', {'url':url, 'text':text, 'xml_file':object, 'CPVisibility':'hidden', 'RPVisibility':'visible'})

inpresystem/templates/main/index.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<title>Менеджер текстов</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'main/css/font-awesome.min.css' %}" rel="stylesheet">
<link href="{% static 'main/css/Project.css' %}" rel="stylesheet">
<link href="{% static 'main/css/index.css' %}" rel="stylesheet">
<script src="{% static 'main/js/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'main/js/wb.overlay.min.js' %}"></script>
<script>
$(document).ready(function()
{
   var $overlaymenu = $('#OverlayMenu1-overlay');
   $overlaymenu.overlay({'hideTransition':true});
   $('#OverlayMenu1').on('click', function(e)
   {
      $.overlay.show($overlaymenu);
      return false;
   });
});
</script>
</head>
<body>
<div id="PageHeader">
<div id="wb_OverlayMenu1">
<a href="#" id="OverlayMenu1">
<span class="line"></span>
<span class="line">
</span><span class="line"></span>
</a>
</div>
<div id="wb_Logo">
<h1 id="Logo">XMLТекст</h1></div>
</div>
<div id="wb_Text1">
<span style="color:#000000;font-family:Arial;font-size:13px;">Double click to edit</span></div>

<select name="ProjectsList" size="24" id="Combobox1" autocomplete="off" onchange="location = this.value">
   {% if xml_file %}
		{% for doc in xml_file.actual_list_of_objects %}
         <option value="{{url}}view_{{doc.id}}">{{doc.title}}</option>
		{% endfor %}
	{% endif %}
</select>

<form action="{% url 'main:create_text_button' %}" method="POST">
	{% csrf_token %}
	<input type="submit" id="Button1" name="ButtonCreatetext" value="Добавить новый текст">
</form>

<form action="{% url 'main:find_button' %}" method="POST">
	{% csrf_token %}
   <input style="visibility:inherit" type="text" id="EditboxFind"  name="find" value="{{xml_file.find_string}}" maxlength="255" spellcheck="false">
	<input type="submit" id="ButtonFind" name="ButtonFind" value="Найти">
</form>

<form action="{% url 'main:sort_button' %}" method="POST">
	{% csrf_token %}
	<input type="submit" id="ButtonSort" name="ButtonSort" value="Сортировать">
</form>

<div id="MainLayer">
   <div id="CPLayer" style="visibility:{{CPVisibility}}">
      <form action="{% url 'main:create_text' %}" method="POST">
         {% csrf_token %}
         <label style="visibility:inherit" for="" id="Label10">Создание текста</label>
         
         <label style="visibility:inherit" for="" id="Label8">Заголовок:</label>
         <label style="visibility:inherit" for="" id="Label9">Источник:</label>
         <label style="visibility:inherit" for="" id="Label11">Категория:</label>
         <label style="visibility:inherit" for="" id="Label12">Дата публикации:</label>
         <label style="visibility:inherit" for="" id="Label13">Идентификатор:</label>

         <input style="visibility:inherit" type="text" id="Editbox6"  name="title" value="" maxlength="255" spellcheck="false">
         <input style="visibility:inherit" type="text" id="Editbox7"  name="source" value="" maxlength="255" spellcheck="false">
         <input style="visibility:inherit" type="text" id="Editbox8"  name="category" value="" spellcheck="false" min="0">
         <input style="visibility:inherit" type="text" id="Editbox9"  name="published" value="" spellcheck="false" min="0">
         <input style="visibility:inherit" type="text" id="Editbox10" name="id" value="" readonly spellcheck="false" min="0">
         
         <textarea style="visibility:inherit; overflow:auto;" type="text" id="Editbox11" name="text" spellcheck="false" min="0"></textarea>>

         <input style="visibility:inherit" type="submit" id="Button3" name="Save" value="Создать текст">
      </form>
   </div>
   <div id="RPLayer" style="visibility:{{RPVisibility}}">
      <form action="{{url}}save_{{text.id}}/" method="POST">
         {% csrf_token %}
         <label style="visibility:inherit" for="" id="Label10">Обзор текста</label>
         
         <label style="visibility:inherit" for="" id="Label8">Заголовок:</label>
         <label style="visibility:inherit" for="" id="Label9">Источник:</label>
         <label style="visibility:inherit" for="" id="Label11">Категория:</label>
         <label style="visibility:inherit" for="" id="Label12">Дата публикации:</label>
         <label style="visibility:inherit" for="" id="Label13">Идентификатор:</label>

         <input style="visibility:inherit" type="text" id="Editbox6"  name="title" value="{{text.title}}" maxlength="255" spellcheck="false">
         <input style="visibility:inherit" type="text" id="Editbox7"  name="source" value="{{text.source}}" maxlength="255" spellcheck="false">
         <input style="visibility:inherit" type="text" id="Editbox8"  name="category" value="{{text.category}}" spellcheck="false" min="0">
         <input style="visibility:inherit" type="text" id="Editbox9"  name="published" value="{{text.published}}" spellcheck="false" min="0">
         <input style="visibility:inherit" type="text" id="Editbox10" name="id" value="{{text.id}}" readonly spellcheck="false" min="0">
         
         <textarea style="visibility:inherit; overflow:auto;" type="text" id="Editbox11" name="text" spellcheck="false" min="0">{{text.text}}</textarea>>

         <input style="visibility:inherit" type="submit" id="Button3" name="Save" value="Сохранить изменения">
      </form>
      <form action="{{url}}delete_{{text.id}}/" method="POST">
         {% csrf_token %}
         <input style="visibility:inherit" type="submit" id="Button4" name="Delete" value="Удалить текст">
      </form>
   </div>
</div>
<div id="PageFooter_sensitive"></div>
<div id="PageFooter">
</div>
<div id="OverlayMenu1-overlay">
<div class="OverlayMenu1">
<ul class="drilldown-menu" role="menu">
<li><a role="menuitem" href="#"><i class="fa fa-home overlay-icon"></i>&#1043;&#1083;&#1072;&#1074;&#1085;&#1072;&#1103;</a></li>
<li><a role="menuitem" href="#"><i class="fa fa-user overlay-icon"></i>&#1054;&nbsp;&#1087;&#1088;&#1086;&#1077;&#1082;&#1090;&#1077;</a></li>
   </ul>
</div>
<a class="close-button" id="OverlayMenu1-close" href="#" role="button" aria-hidden="true"><span></span></a>
</div>
</body>
</html>